import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import Aimarea from '../components/Aimarea'
import Clicker from '../components/Clicker'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Clicker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Clicker/>
      {/* <Aimarea/> */}

    </div>
  )
}

export default Home
